name: ewrii
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  share: ^2.0.4
  url_launcher: ^6.1.4
  cupertino_icons: ^1.0.8
  flutter_pdfview: ^1.3.0  # Adicione esta linha:
  dio: ^5.1.0
  path_provider: ^2.0.10
  permission_handler: ^10.2.0
  open_file: ^3.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


